"""create at ingredient_temp

Revision ID: 248fb1bb9b26
Revises: 
Create Date: 2025-10-15 20:02:16.716180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248fb1bb9b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients_temp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'recipe_temp', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients_temp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amount')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
