"""add num_peplie

Revision ID: 4e149338288a
Revises: 248fb1bb9b26
Create Date: 2025-10-15 22:08:17.911388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e149338288a'
down_revision = '248fb1bb9b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_temp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_people', sa.String(length=20),server_default='2人分', nullable=False))

    # ### end Alembic commands ###
    op.alter_column('recipe_temp', 'num_people', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_temp', schema=None) as batch_op:
        batch_op.drop_column('num_people')

    # ### end Alembic commands ###
