"""make Steps Table

Revision ID: 56fb5a84a333
Revises: 4e149338288a
Create Date: 2025-10-15 22:33:24.817220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fb5a84a333'
down_revision = '4e149338288a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.String(length=100), nullable=False),
    sa.Column('instruction', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_temp.id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    with op.batch_alter_table('recipe_temp', schema=None) as batch_op:
        batch_op.alter_column('num_people',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_temp', schema=None) as batch_op:
        batch_op.alter_column('num_people',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.drop_table('steps')
    # ### end Alembic commands ###
